server:
  port: 8081  # <-- puerto propio del microservicio de autenticación

spring:
  application:
    name: "crediya_auth"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false            # opcional: desactiva H2 si no lo usas
  profiles:
    include: null

  # R2DBC estándar (Spring Boot)
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/auth_user
    username: postgres
    password: "1234"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"

routes:
  paths:
    users: "/api/v1/users"

# Mantengo también tus propiedades personalizadas (si tu adapter las usa)
adapters:
  r2dbc:
    host: "localhost"
    port: 5435
    database: "auth_user"
    schema: "public"
    username: "postgres"
    password: "1234"
