server:
  port: 8081

spring:
  application:
    name: "crediya_auth"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
  profiles:
    include: null

  # R2DBC estándar (Spring Boot)
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/auth_user
    username: postgres
    password: "1234"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"

routes:
  paths:
    users:
      users: "/api/v1/usuarios"
      findByEmail: "/api/v1/usuarios/{email}"
      existsByEmailAndDocument: "/api/v1/usuarios/exists"
    auth:
      login: "/api/v1/login"
      isEmailEqualToToken: "/api/v1/auth/equal-email"
      roleByAuthHeaderToken: "/api/v1/auth/role"

adapters:
  r2dbc:
    host: "localhost"
    port: 5435
    database: "auth_user"
    schema: "public"
    username: "postgres"
    password: "1234"
jwt:
  secret: uFI2TjnGi3wC9pzQ3urYEyreDGDiYtYoBNelOQRclVzcmJTRDPOSUyY3HrLQGhw5
  expiredMinutes: 400
